# Generated by Django 3.2.6 on 2021-08-17 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='boy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='الاسم')),
                ('age', models.IntegerField(verbose_name='السن')),
                ('number_kawme', models.IntegerField(verbose_name='الرقم القومي')),
                ('number_phone', models.IntegerField(verbose_name='رقم الوالد او الوالدة')),
                ('image', models.ImageField(upload_to='', verbose_name='صورة الطفل')),
            ],
        ),
    ]
