# Generated by Django 3.2.6 on 2021-08-17 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='techers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='الاسم')),
                ('qualification', models.CharField(max_length=50, verbose_name='المؤهل')),
                ('number_kawme', models.IntegerField(verbose_name='الرقم القومي')),
                ('Salary', models.IntegerField(verbose_name='المرتب الشهري')),
                ('number_phone', models.IntegerField(verbose_name='رقم هاتف المعلمة')),
            ],
            options={
                'verbose_name_plural': 'techers',
            },
        ),
        migrations.CreateModel(
            name='classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='اسم الفصل')),
                ('techer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home_app.techers', verbose_name='المعلمة')),
            ],
        ),
    ]
