# Generated by Django 3.2.6 on 2021-08-17 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0003_boy_boy_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excuse', models.BooleanField(default=True, verbose_name='بعذر ام لا')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home_app.boy', verbose_name='الاسم')),
            ],
            options={
                'verbose_name': 'absence',
                'verbose_name_plural': 'absences',
            },
        ),
    ]
