# Generated by Django 3.2.6 on 2021-08-18 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0004_absence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boy',
            name='image',
            field=models.ImageField(upload_to='boys_images/', verbose_name='صورة الطفل'),
        ),
    ]
