# Generated by Django 3.2.6 on 2021-08-18 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0005_alter_boy_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='الاسم')),
                ('number_kawme', models.IntegerField(verbose_name='الرقم القومي')),
                ('number_phone', models.IntegerField(verbose_name='رقم الهاتف')),
                ('Salary', models.IntegerField(verbose_name='المرتب الشهري')),
                ('image', models.ImageField(blank=True, null=True, upload_to='boys_images/', verbose_name='صورة السائق')),
            ],
            options={
                'verbose_name': 'driver',
                'verbose_name_plural': 'drivers',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='boy',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='boys_images/', verbose_name='صورة الطفل'),
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('bus', 'bus'), ('tok tok', 'tok tok'), ('car', 'car')], max_length=50, verbose_name='نوع وسيلة النقل')),
                ('number', models.CharField(max_length=20, verbose_name='الرقم التعريفي')),
                ('driver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home_app.driver', verbose_name='السائق')),
            ],
            options={
                'verbose_name': 'Transport',
                'verbose_name_plural': 'Transports',
            },
        ),
    ]
