# Generated by Django 3.2.6 on 2021-08-18 13:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home_app', '0009_alter_profile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='boy',
            name='user',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='المستخدم'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driver',
            name='user',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='المستخدم'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='techers',
            name='user',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='المستخدم'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transport',
            name='user',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='المستخدم'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transport',
            name='kind',
            field=models.CharField(choices=[('bus', 'bus'), ('tok tok', 'tok tok'), ('car', 'car')], max_length=50, verbose_name='نوع وسيلة النقل'),
        ),
    ]
