# Generated by Django 3.2.7 on 2021-09-03 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0012_auto_20210829_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='techers',
            name='age',
            field=models.IntegerField(default='1', verbose_name='السن'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transport',
            name='kind',
            field=models.CharField(choices=[('bus', 'bus'), ('tok tok', 'tok tok'), ('car', 'car')], max_length=50, verbose_name='نوع وسيلة النقل'),
        ),
    ]
