# Generated by Django 3.2.7 on 2021-09-08 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0013_auto_20210903_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='boy',
            name='paid',
            field=models.IntegerField(default='1', verbose_name='المبلغ المدفع'),
            preserve_default=False,
        ),
    ]
