# Generated by Django 3.2.7 on 2021-09-08 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0014_boy_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='techers',
            name='rateb',
            field=models.IntegerField(default='1', verbose_name='الراتب السنوي'),
            preserve_default=False,
        ),
    ]
