# Generated by Django 3.2.7 on 2021-09-09 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0015_techers_rateb'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='rateb',
            field=models.IntegerField(blank=True, null=True, verbose_name='الراتب السنوي'),
        ),
        migrations.AlterField(
            model_name='techers',
            name='rateb',
            field=models.IntegerField(blank=True, null=True, verbose_name='الراتب السنوي'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='kind',
            field=models.CharField(choices=[('bus', 'bus'), ('car', 'car'), ('tok tok', 'tok tok')], max_length=50, verbose_name='نوع وسيلة النقل'),
        ),
    ]
