# Generated by Django 3.2.7 on 2021-09-09 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0017_auto_20210909_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='التاريخ'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='kind',
            field=models.CharField(choices=[('bus', 'bus'), ('tok tok', 'tok tok'), ('car', 'car')], max_length=50, verbose_name='نوع وسيلة النقل'),
        ),
    ]
