# Generated by Django 3.2.7 on 2021-09-18 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0019_auto_20210910_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default='1', max_length=50, verbose_name='اسم الروضة'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='boy',
            name='boy_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home_app.classes', verbose_name='الفصل'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.ImageField(upload_to='user_img/', verbose_name='شعار الروضة'),
        ),
    ]
