# Generated by Django 3.2.7 on 2021-09-26 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0026_auto_20210926_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='darajat',
            name='add_date',
            field=models.DateField(blank=True, null=True, verbose_name='التاريخ'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='kind',
            field=models.CharField(choices=[('tok tok', 'tok tok'), ('bus', 'bus'), ('car', 'car')], max_length=50, verbose_name='نوع وسيلة النقل'),
        ),
    ]
