# Generated by Django 3.2.7 on 2021-09-29 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0027_auto_20210926_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='darajat',
            name='daraja4',
            field=models.IntegerField(blank=True, default='0', null=True, verbose_name='درجة الطالب'),
        ),
        migrations.AlterField(
            model_name='darajat',
            name='daraja5',
            field=models.IntegerField(blank=True, default='0', null=True, verbose_name='درجة الطالب'),
        ),
        migrations.AlterField(
            model_name='darajat',
            name='daraja6',
            field=models.IntegerField(blank=True, default='0', null=True, verbose_name='درجة الطالب'),
        ),
        migrations.AlterField(
            model_name='darajat',
            name='daraja7',
            field=models.IntegerField(blank=True, default='0', null=True, verbose_name='درجة الطالب'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='kind',
            field=models.CharField(choices=[('bus', 'bus'), ('car', 'car'), ('tok tok', 'tok tok')], max_length=50, verbose_name='نوع وسيلة النقل'),
        ),
    ]
