# Generated by Django 3.2.7 on 2022-01-15 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0029_auto_20210929_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='name_of_admin',
            field=models.CharField(default=1, max_length=50, verbose_name='اسم المشرف'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transport',
            name='kind',
            field=models.CharField(choices=[('tok tok', 'tok tok'), ('car', 'car'), ('bus', 'bus')], max_length=50, verbose_name='نوع وسيلة النقل'),
        ),
    ]
