# Generated by Django 4.0.1 on 2022-01-20 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0030_auto_20220115_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='techers',
            name='her_class',
            field=models.ForeignKey(default='5', on_delete=django.db.models.deletion.CASCADE, to='home_app.classes', verbose_name='الفصل'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transport',
            name='kind',
            field=models.CharField(choices=[('bus', 'bus'), ('tok tok', 'tok tok'), ('car', 'car')], max_length=50, verbose_name='نوع وسيلة النقل'),
        ),
    ]
