# Generated by Django 4.0.1 on 2022-01-23 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0031_techers_her_class_alter_transport_kind'),
    ]

    operations = [
        migrations.RenameField(
            model_name='absence',
            old_name='date',
            new_name='created',
        ),
        migrations.AlterField(
            model_name='transport',
            name='kind',
            field=models.CharField(choices=[('tok tok', 'tok tok'), ('bus', 'bus'), ('car', 'car')], max_length=50, verbose_name='نوع وسيلة النقل'),
        ),
    ]
