# Generated by Django 4.0.1 on 2022-01-27 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0033_alter_transport_kind'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='techers',
            name='her_class',
        ),
        migrations.AlterField(
            model_name='transport',
            name='kind',
            field=models.CharField(choices=[('اتوبيس', 'اتوبيس'), ('تكتك', 'تكتك'), ('ميكروباس', 'ميكروباس'), ('سيارة', 'سيارة')], max_length=50, verbose_name='نوع وسيلة النقل'),
        ),
    ]
