# Generated by Django 4.0.1 on 2022-01-27 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0035_alter_boy_boy_class_alter_transport_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='techer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='home_app.techers', verbose_name='المعلمة'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='kind',
            field=models.CharField(choices=[('ميكروباس', 'ميكروباس'), ('اتوبيس', 'اتوبيس'), ('سيارة', 'سيارة'), ('تكتك', 'تكتك')], max_length=50, verbose_name='نوع وسيلة النقل'),
        ),
    ]
