# Generated by Django 4.0.1 on 2022-03-02 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0037_alter_classes_techer_alter_transport_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='mawad',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='transport',
            name='kind',
            field=models.CharField(choices=[('سيارة', 'سيارة'), ('تكتك', 'تكتك'), ('اتوبيس', 'اتوبيس'), ('ميكروباس', 'ميكروباس')], max_length=50, verbose_name='نوع وسيلة النقل'),
        ),
    ]
