# Generated by Django 4.0.1 on 2022-05-15 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0040_remove_darajat_profile_alter_boy_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='darajat',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home_app.profile', verbose_name='profile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transport',
            name='kind',
            field=models.CharField(choices=[('تكتك', 'تكتك'), ('اتوبيس', 'اتوبيس'), ('سيارة', 'سيارة'), ('ميكروباس', 'ميكروباس')], max_length=50, verbose_name='نوع وسيلة النقل'),
        ),
    ]
