# Generated by Django 4.0.4 on 2022-05-25 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0042_alter_transport_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='العنوان'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='user_img/', verbose_name='شعار الروضة'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='اسم الروضة'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name_of_admin',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='اسم المشرف'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='kind',
            field=models.CharField(choices=[('ميكروباس', 'ميكروباس'), ('اتوبيس', 'اتوبيس'), ('تكتك', 'تكتك'), ('سيارة', 'سيارة')], max_length=50, verbose_name='نوع وسيلة النقل'),
        ),
    ]
