# Generated by Django 4.0.4 on 2022-05-25 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0043_alter_profile_city_alter_profile_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transport',
            name='kind',
            field=models.CharField(choices=[('ميكروباس', 'ميكروباس'), ('اتوبيس', 'اتوبيس'), ('سيارة', 'سيارة'), ('تكتك', 'تكتك')], max_length=50, verbose_name='نوع وسيلة النقل'),
        ),
    ]
