# Generated by Django 4.0.4 on 2022-05-25 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0046_alter_transport_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transport',
            name='kind',
            field=models.CharField(choices=[('ميكروباس', 'ميكروباس'), ('سيارة', 'سيارة'), ('تكتك', 'تكتك'), ('اتوبيس', 'اتوبيس')], max_length=50, verbose_name='نوع وسيلة النقل'),
        ),
    ]
