# Generated by Django 4.0.4 on 2022-05-26 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0047_alter_transport_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='working_months',
            field=models.IntegerField(blank=True, null=True, verbose_name='عدد اشهر العمل'),
        ),
        migrations.AddField(
            model_name='profile',
            name='year_expenses',
            field=models.IntegerField(blank=True, null=True, verbose_name='سعر الاشتراك السنوي'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='kind',
            field=models.CharField(choices=[('ميكروباس', 'ميكروباس'), ('اتوبيس', 'اتوبيس'), ('تكتك', 'تكتك'), ('سيارة', 'سيارة')], max_length=50, verbose_name='نوع وسيلة النقل'),
        ),
    ]
