# Generated by Django 4.0.4 on 2022-05-26 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0048_profile_working_months_profile_year_expenses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boy',
            name='Remaining_amount',
            field=models.IntegerField(blank=True, null=True, verbose_name='المبلغ المتبقي'),
        ),
        migrations.AddField(
            model_name='boy',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home_app.profile', verbose_name='المستخدم'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transport',
            name='kind',
            field=models.CharField(choices=[('اتوبيس', 'اتوبيس'), ('ميكروباس', 'ميكروباس'), ('سيارة', 'سيارة'), ('تكتك', 'تكتك')], max_length=50, verbose_name='نوع وسيلة النقل'),
        ),
    ]
