# Generated by Django 4.0.4 on 2022-05-26 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0049_boy_remaining_amount_boy_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home_app.profile', verbose_name='المستخدم'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='techers',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home_app.profile', verbose_name='المستخدم'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transport',
            name='kind',
            field=models.CharField(choices=[('ميكروباس', 'ميكروباس'), ('سيارة', 'سيارة'), ('اتوبيس', 'اتوبيس'), ('تكتك', 'تكتك')], max_length=50, verbose_name='نوع وسيلة النقل'),
        ),
    ]
