# Generated by Django 4.0.4 on 2022-05-26 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0050_driver_profile_techers_profile_alter_transport_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transport',
            name='kind',
            field=models.CharField(choices=[('اتوبيس', 'اتوبيس'), ('تكتك', 'تكتك'), ('ميكروباس', 'ميكروباس'), ('سيارة', 'سيارة')], max_length=50, verbose_name='نوع وسيلة النقل'),
        ),
    ]
