# Generated by Django 4.0.4 on 2022-05-28 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0053_absence_semester_boy_semester_classes_semester_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='absence',
            name='academic_year',
            field=models.CharField(blank=True, choices=[('2022', '2022-2023'), ('2021', '2021-2022'), ('2023', '2023-2024'), ('2024', '2024-2025')], max_length=50, null=True, verbose_name='السنة الدراسية'),
        ),
        migrations.AddField(
            model_name='boy',
            name='academic_year',
            field=models.CharField(blank=True, choices=[('2022', '2022-2023'), ('2021', '2021-2022'), ('2023', '2023-2024'), ('2024', '2024-2025')], max_length=50, null=True, verbose_name='السنة الدراسية'),
        ),
        migrations.AddField(
            model_name='classes',
            name='academic_year',
            field=models.CharField(blank=True, choices=[('2022', '2022-2023'), ('2021', '2021-2022'), ('2023', '2023-2024'), ('2024', '2024-2025')], max_length=50, null=True, verbose_name='السنة الدراسية'),
        ),
        migrations.AddField(
            model_name='darajat',
            name='academic_year',
            field=models.CharField(blank=True, choices=[('2022', '2022-2023'), ('2021', '2021-2022'), ('2023', '2023-2024'), ('2024', '2024-2025')], max_length=50, null=True, verbose_name='السنة الدراسية'),
        ),
        migrations.AddField(
            model_name='driver',
            name='academic_year',
            field=models.CharField(blank=True, choices=[('2022', '2022-2023'), ('2021', '2021-2022'), ('2023', '2023-2024'), ('2024', '2024-2025')], max_length=50, null=True, verbose_name='السنة الدراسية'),
        ),
        migrations.AddField(
            model_name='masrof',
            name='academic_year',
            field=models.CharField(blank=True, choices=[('2022', '2022-2023'), ('2021', '2021-2022'), ('2023', '2023-2024'), ('2024', '2024-2025')], max_length=50, null=True, verbose_name='السنة الدراسية'),
        ),
        migrations.AddField(
            model_name='mawad',
            name='academic_year',
            field=models.CharField(blank=True, choices=[('2022', '2022-2023'), ('2021', '2021-2022'), ('2023', '2023-2024'), ('2024', '2024-2025')], max_length=50, null=True, verbose_name='السنة الدراسية'),
        ),
        migrations.AddField(
            model_name='profile',
            name='academic_year',
            field=models.CharField(choices=[('2022', '2022-2023'), ('2021', '2021-2022'), ('2023', '2023-2024'), ('2024', '2024-2025')], default=1, max_length=50, verbose_name='السنة الدراسية'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='techers',
            name='academic_year',
            field=models.CharField(blank=True, choices=[('2022', '2022-2023'), ('2021', '2021-2022'), ('2023', '2023-2024'), ('2024', '2024-2025')], max_length=50, null=True, verbose_name='السنة الدراسية'),
        ),
        migrations.AddField(
            model_name='transport',
            name='academic_year',
            field=models.CharField(blank=True, choices=[('2022', '2022-2023'), ('2021', '2021-2022'), ('2023', '2023-2024'), ('2024', '2024-2025')], max_length=50, null=True, verbose_name='السنة الدراسية'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='kind',
            field=models.CharField(choices=[('تكتك', 'تكتك'), ('اتوبيس', 'اتوبيس'), ('ميكروباس', 'ميكروباس'), ('سيارة', 'سيارة')], max_length=50, verbose_name='نوع وسيلة النقل'),
        ),
    ]
