# Generated by Django 4.0.4 on 2022-05-28 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home_app', '0054_absence_academic_year_boy_academic_year_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='absence',
            name='academic_year',
        ),
        migrations.RemoveField(
            model_name='boy',
            name='academic_year',
        ),
        migrations.RemoveField(
            model_name='classes',
            name='academic_year',
        ),
        migrations.RemoveField(
            model_name='darajat',
            name='academic_year',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='academic_year',
        ),
        migrations.RemoveField(
            model_name='masrof',
            name='academic_year',
        ),
        migrations.RemoveField(
            model_name='mawad',
            name='academic_year',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='academic_year',
        ),
        migrations.RemoveField(
            model_name='techers',
            name='academic_year',
        ),
        migrations.RemoveField(
            model_name='transport',
            name='academic_year',
        ),
        migrations.AddField(
            model_name='absence',
            name='year',
            field=models.CharField(blank=True, choices=[('2024', '2024-2025'), ('2022', '2022-2023'), ('2023', '2023-2024'), ('2021', '2021-2022')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='boy',
            name='year',
            field=models.CharField(blank=True, choices=[('2024', '2024-2025'), ('2022', '2022-2023'), ('2023', '2023-2024'), ('2021', '2021-2022')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='classes',
            name='year',
            field=models.CharField(blank=True, choices=[('2024', '2024-2025'), ('2022', '2022-2023'), ('2023', '2023-2024'), ('2021', '2021-2022')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='darajat',
            name='year',
            field=models.CharField(blank=True, choices=[('2024', '2024-2025'), ('2022', '2022-2023'), ('2023', '2023-2024'), ('2021', '2021-2022')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='year',
            field=models.CharField(blank=True, choices=[('2024', '2024-2025'), ('2022', '2022-2023'), ('2023', '2023-2024'), ('2021', '2021-2022')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='masrof',
            name='year',
            field=models.CharField(blank=True, choices=[('2024', '2024-2025'), ('2022', '2022-2023'), ('2023', '2023-2024'), ('2021', '2021-2022')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mawad',
            name='year',
            field=models.CharField(blank=True, choices=[('2024', '2024-2025'), ('2022', '2022-2023'), ('2023', '2023-2024'), ('2021', '2021-2022')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='techers',
            name='year',
            field=models.CharField(blank=True, choices=[('2024', '2024-2025'), ('2022', '2022-2023'), ('2023', '2023-2024'), ('2021', '2021-2022')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='transport',
            name='year',
            field=models.CharField(blank=True, choices=[('2024', '2024-2025'), ('2022', '2022-2023'), ('2023', '2023-2024'), ('2021', '2021-2022')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='transport',
            name='kind',
            field=models.CharField(choices=[('اتوبيس', 'اتوبيس'), ('سيارة', 'سيارة'), ('ميكروباس', 'ميكروباس'), ('تكتك', 'تكتك')], max_length=50, verbose_name='نوع وسيلة النقل'),
        ),
        migrations.CreateModel(
            name='Monthly_exams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(blank=True, choices=[('6', 'يونيو'), ('12', 'ديسمبر'), ('7', 'يوليو'), ('9', 'سبتمبر'), ('8', 'أغسطس'), ('1', 'يناير'), ('2', 'فبراير'), ('5', 'مايو'), ('10', 'أكتوبر'), ('11', 'نوفمبر'), ('3', 'مارس'), ('4', 'أبريل')], max_length=50, null=True)),
                ('year', models.CharField(blank=True, choices=[('2024', '2024-2025'), ('2022', '2022-2023'), ('2023', '2023-2024'), ('2021', '2021-2022')], max_length=50, null=True)),
                ('daraja', models.IntegerField(verbose_name='درجة الطالب')),
                ('daraja1', models.IntegerField(verbose_name='درجة الطالب')),
                ('daraja2', models.IntegerField(verbose_name='درجة الطالب')),
                ('daraja3', models.IntegerField(verbose_name='درجة الطالب')),
                ('daraja4', models.IntegerField(blank=True, default='0', null=True, verbose_name='درجة الطالب')),
                ('daraja5', models.IntegerField(blank=True, default='0', null=True, verbose_name='درجة الطالب')),
                ('daraja6', models.IntegerField(blank=True, default='0', null=True, verbose_name='درجة الطالب')),
                ('daraja7', models.IntegerField(blank=True, default='0', null=True, verbose_name='درجة الطالب')),
                ('nesba', models.IntegerField(blank=True, null=True)),
                ('ejamly_darajat', models.IntegerField(blank=True, null=True)),
                ('ejamly_total', models.IntegerField(blank=True, null=True)),
                ('add_date', models.DateField(blank=True, null=True, verbose_name='التاريخ')),
                ('mada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home_app.mawad', verbose_name='المادة')),
                ('mada1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='month_mada1', to='home_app.mawad', verbose_name='المادة')),
                ('mada2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='month_mada2', to='home_app.mawad', verbose_name='المادة')),
                ('mada3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='month_mada3', to='home_app.mawad', verbose_name='المادة')),
                ('mada4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='month_mada4', to='home_app.mawad', verbose_name='المادة')),
                ('mada5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='month_mada5', to='home_app.mawad', verbose_name='المادة')),
                ('mada6', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='month_mada6', to='home_app.mawad', verbose_name='المادة')),
                ('mada7', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='month_mada7', to='home_app.mawad', verbose_name='المادة')),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home_app.boy', verbose_name='اسم الطالب')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home_app.profile', verbose_name='المستخدم')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
        ),
    ]
