# Generated by Django 4.0.4 on 2022-05-29 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0055_remove_absence_academic_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boy',
            name='Date_of_Birth',
            field=models.DateField(null=True, verbose_name='تاريخ الميلاد'),
        ),
        migrations.AddField(
            model_name='boy',
            name='addres',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='العنوان'),
        ),
        migrations.AddField(
            model_name='boy',
            name='allergy',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='لديه حساسية'),
        ),
        migrations.AddField(
            model_name='boy',
            name='bus_subscriber',
            field=models.BooleanField(default=False, verbose_name='مشترك بالاتوبيس'),
        ),
        migrations.AddField(
            model_name='boy',
            name='kind',
            field=models.CharField(choices=[('2', 'انثى'), ('1', 'ذكر')], default='1', max_length=50, verbose_name='النوع'),
        ),
        migrations.AddField(
            model_name='boy',
            name='kind_of_sick',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='المرض'),
        ),
        migrations.AddField(
            model_name='boy',
            name='other_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='رقم أخر'),
        ),
        migrations.AddField(
            model_name='boy',
            name='paids',
            field=models.BooleanField(default=False, null=True, verbose_name='تم الدفع'),
        ),
        migrations.AddField(
            model_name='boy',
            name='price_of_bus',
            field=models.IntegerField(default=0, verbose_name='سعر اشتراك الاتوبيس'),
        ),
        migrations.AddField(
            model_name='boy',
            name='sick',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='يعناي الطفل من امراض اخرى'),
        ),
        migrations.AlterField(
            model_name='absence',
            name='semester',
            field=models.CharField(blank=True, choices=[('second', 'الفصل الدراسي الثاني'), ('first', 'الفصل الدراسي الاول')], max_length=50, null=True, verbose_name='الفصل الدراسي'),
        ),
        migrations.AlterField(
            model_name='absence',
            name='year',
            field=models.CharField(blank=True, choices=[('2023', '2023-2024'), ('2021', '2021-2022'), ('2022', '2022-2023'), ('2024', '2024-2025')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='boy',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name='السن'),
        ),
        migrations.AlterField(
            model_name='boy',
            name='number_kawme',
            field=models.IntegerField(blank=True, null=True, verbose_name='الرقم القومي'),
        ),
        migrations.AlterField(
            model_name='boy',
            name='number_phone',
            field=models.IntegerField(blank=True, null=True, verbose_name='رقم ولي الامر'),
        ),
        migrations.AlterField(
            model_name='boy',
            name='semester',
            field=models.CharField(blank=True, choices=[('second', 'الفصل الدراسي الثاني'), ('first', 'الفصل الدراسي الاول')], max_length=50, null=True, verbose_name='الفصل الدراسي'),
        ),
        migrations.AlterField(
            model_name='boy',
            name='year',
            field=models.CharField(blank=True, choices=[('2023', '2023-2024'), ('2021', '2021-2022'), ('2022', '2022-2023'), ('2024', '2024-2025')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='classes',
            name='semester',
            field=models.CharField(blank=True, choices=[('second', 'الفصل الدراسي الثاني'), ('first', 'الفصل الدراسي الاول')], max_length=50, null=True, verbose_name='الفصل الدراسي'),
        ),
        migrations.AlterField(
            model_name='classes',
            name='year',
            field=models.CharField(blank=True, choices=[('2023', '2023-2024'), ('2021', '2021-2022'), ('2022', '2022-2023'), ('2024', '2024-2025')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='darajat',
            name='semester',
            field=models.CharField(blank=True, choices=[('second', 'الفصل الدراسي الثاني'), ('first', 'الفصل الدراسي الاول')], max_length=50, null=True, verbose_name='الفصل الدراسي'),
        ),
        migrations.AlterField(
            model_name='darajat',
            name='year',
            field=models.CharField(blank=True, choices=[('2023', '2023-2024'), ('2021', '2021-2022'), ('2022', '2022-2023'), ('2024', '2024-2025')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='semester',
            field=models.CharField(blank=True, choices=[('second', 'الفصل الدراسي الثاني'), ('first', 'الفصل الدراسي الاول')], max_length=50, null=True, verbose_name='الفصل الدراسي'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='year',
            field=models.CharField(blank=True, choices=[('2023', '2023-2024'), ('2021', '2021-2022'), ('2022', '2022-2023'), ('2024', '2024-2025')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='masrof',
            name='semester',
            field=models.CharField(blank=True, choices=[('second', 'الفصل الدراسي الثاني'), ('first', 'الفصل الدراسي الاول')], max_length=50, null=True, verbose_name='الفصل الدراسي'),
        ),
        migrations.AlterField(
            model_name='masrof',
            name='year',
            field=models.CharField(blank=True, choices=[('2023', '2023-2024'), ('2021', '2021-2022'), ('2022', '2022-2023'), ('2024', '2024-2025')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mawad',
            name='semester',
            field=models.CharField(blank=True, choices=[('second', 'الفصل الدراسي الثاني'), ('first', 'الفصل الدراسي الاول')], max_length=50, null=True, verbose_name='الفصل الدراسي'),
        ),
        migrations.AlterField(
            model_name='mawad',
            name='year',
            field=models.CharField(blank=True, choices=[('2023', '2023-2024'), ('2021', '2021-2022'), ('2022', '2022-2023'), ('2024', '2024-2025')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='monthly_exams',
            name='month',
            field=models.CharField(blank=True, choices=[('9', 'سبتمبر'), ('5', 'مايو'), ('10', 'أكتوبر'), ('3', 'مارس'), ('4', 'أبريل'), ('6', 'يونيو'), ('11', 'نوفمبر'), ('8', 'أغسطس'), ('12', 'ديسمبر'), ('2', 'فبراير'), ('7', 'يوليو'), ('1', 'يناير')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='monthly_exams',
            name='year',
            field=models.CharField(blank=True, choices=[('2023', '2023-2024'), ('2021', '2021-2022'), ('2022', '2022-2023'), ('2024', '2024-2025')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='semester',
            field=models.CharField(choices=[('second', 'الفصل الدراسي الثاني'), ('first', 'الفصل الدراسي الاول')], max_length=50, verbose_name='الفصل الدراسي'),
        ),
        migrations.AlterField(
            model_name='techers',
            name='semester',
            field=models.CharField(blank=True, choices=[('second', 'الفصل الدراسي الثاني'), ('first', 'الفصل الدراسي الاول')], max_length=50, null=True, verbose_name='الفصل الدراسي'),
        ),
        migrations.AlterField(
            model_name='techers',
            name='year',
            field=models.CharField(blank=True, choices=[('2023', '2023-2024'), ('2021', '2021-2022'), ('2022', '2022-2023'), ('2024', '2024-2025')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='transport',
            name='kind',
            field=models.CharField(choices=[('اتوبيس', 'اتوبيس'), ('تكتك', 'تكتك'), ('سيارة', 'سيارة'), ('ميكروباس', 'ميكروباس')], max_length=50, verbose_name='نوع وسيلة النقل'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='semester',
            field=models.CharField(blank=True, choices=[('second', 'الفصل الدراسي الثاني'), ('first', 'الفصل الدراسي الاول')], max_length=50, null=True, verbose_name='الفصل الدراسي'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='year',
            field=models.CharField(blank=True, choices=[('2023', '2023-2024'), ('2021', '2021-2022'), ('2022', '2022-2023'), ('2024', '2024-2025')], max_length=50, null=True),
        ),
    ]
