# Generated by Django 4.0.4 on 2022-05-29 12:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home_app', '0057_techers_reward_alter_absence_year_alter_boy_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absence',
            name='year',
            field=models.CharField(blank=True, choices=[('2022', '2022-2023'), ('2024', '2024-2025'), ('2023', '2023-2024'), ('2021', '2021-2022')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='boy',
            name='year',
            field=models.CharField(blank=True, choices=[('2022', '2022-2023'), ('2024', '2024-2025'), ('2023', '2023-2024'), ('2021', '2021-2022')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='classes',
            name='year',
            field=models.CharField(blank=True, choices=[('2022', '2022-2023'), ('2024', '2024-2025'), ('2023', '2023-2024'), ('2021', '2021-2022')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='darajat',
            name='year',
            field=models.CharField(blank=True, choices=[('2022', '2022-2023'), ('2024', '2024-2025'), ('2023', '2023-2024'), ('2021', '2021-2022')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='year',
            field=models.CharField(blank=True, choices=[('2022', '2022-2023'), ('2024', '2024-2025'), ('2023', '2023-2024'), ('2021', '2021-2022')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='masrof',
            name='year',
            field=models.CharField(blank=True, choices=[('2022', '2022-2023'), ('2024', '2024-2025'), ('2023', '2023-2024'), ('2021', '2021-2022')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mawad',
            name='year',
            field=models.CharField(blank=True, choices=[('2022', '2022-2023'), ('2024', '2024-2025'), ('2023', '2023-2024'), ('2021', '2021-2022')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='monthly_exams',
            name='month',
            field=models.CharField(blank=True, choices=[('9', 'سبتمبر'), ('12', 'ديسمبر'), ('6', 'يونيو'), ('5', 'مايو'), ('1', 'يناير'), ('11', 'نوفمبر'), ('8', 'أغسطس'), ('10', 'أكتوبر'), ('3', 'مارس'), ('7', 'يوليو'), ('2', 'فبراير'), ('4', 'أبريل')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='monthly_exams',
            name='year',
            field=models.CharField(blank=True, choices=[('2022', '2022-2023'), ('2024', '2024-2025'), ('2023', '2023-2024'), ('2021', '2021-2022')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='teachers_absence',
            name='month',
            field=models.CharField(blank=True, choices=[('9', 'سبتمبر'), ('12', 'ديسمبر'), ('6', 'يونيو'), ('5', 'مايو'), ('1', 'يناير'), ('11', 'نوفمبر'), ('8', 'أغسطس'), ('10', 'أكتوبر'), ('3', 'مارس'), ('7', 'يوليو'), ('2', 'فبراير'), ('4', 'أبريل')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='teachers_absence',
            name='year',
            field=models.CharField(blank=True, choices=[('2022', '2022-2023'), ('2024', '2024-2025'), ('2023', '2023-2024'), ('2021', '2021-2022')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='techers',
            name='year',
            field=models.CharField(blank=True, choices=[('2022', '2022-2023'), ('2024', '2024-2025'), ('2023', '2023-2024'), ('2021', '2021-2022')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='transport',
            name='kind',
            field=models.CharField(choices=[('اتوبيس', 'اتوبيس'), ('ميكروباس', 'ميكروباس'), ('سيارة', 'سيارة'), ('تكتك', 'تكتك')], max_length=50, verbose_name='نوع وسيلة النقل'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='year',
            field=models.CharField(blank=True, choices=[('2022', '2022-2023'), ('2024', '2024-2025'), ('2023', '2023-2024'), ('2021', '2021-2022')], max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Staff_absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(blank=True, choices=[('9', 'سبتمبر'), ('12', 'ديسمبر'), ('6', 'يونيو'), ('5', 'مايو'), ('1', 'يناير'), ('11', 'نوفمبر'), ('8', 'أغسطس'), ('10', 'أكتوبر'), ('3', 'مارس'), ('7', 'يوليو'), ('2', 'فبراير'), ('4', 'أبريل')], max_length=50, null=True)),
                ('year', models.CharField(blank=True, choices=[('2022', '2022-2023'), ('2024', '2024-2025'), ('2023', '2023-2024'), ('2021', '2021-2022')], max_length=50, null=True)),
                ('excuse', models.BooleanField(default=False, verbose_name='بعذر')),
                ('the_reason', models.CharField(blank=True, max_length=50, null=True, verbose_name='السبب')),
                ('add_date', models.DateField(blank=True, null=True, verbose_name='التاريخ')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home_app.techers', verbose_name='اسم المدرس')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home_app.profile', verbose_name='المستخدم')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='اسم الموظف')),
                ('month', models.CharField(blank=True, choices=[('9', 'سبتمبر'), ('12', 'ديسمبر'), ('6', 'يونيو'), ('5', 'مايو'), ('1', 'يناير'), ('11', 'نوفمبر'), ('8', 'أغسطس'), ('10', 'أكتوبر'), ('3', 'مارس'), ('7', 'يوليو'), ('2', 'فبراير'), ('4', 'أبريل')], max_length=50, null=True)),
                ('year', models.CharField(blank=True, choices=[('2022', '2022-2023'), ('2024', '2024-2025'), ('2023', '2023-2024'), ('2021', '2021-2022')], max_length=50, null=True)),
                ('the_jop', models.CharField(max_length=50, verbose_name='الوظيفة')),
                ('Monthly_Salary', models.IntegerField(verbose_name='المرتب الشهري')),
                ('annual_salary', models.IntegerField(blank=True, null=True, verbose_name='المرتب السنوي')),
                ('add_date', models.DateField(blank=True, null=True, verbose_name='التاريخ')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home_app.profile', verbose_name='المستخدم')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
        ),
    ]
