# Generated by Django 4.0.4 on 2022-06-01 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0058_alter_absence_year_alter_boy_year_alter_classes_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name='السن'),
        ),
        migrations.AlterField(
            model_name='absence',
            name='semester',
            field=models.CharField(blank=True, choices=[('first', 'الفصل الدراسي الاول'), ('second', 'الفصل الدراسي الثاني')], max_length=50, null=True, verbose_name='الفصل الدراسي'),
        ),
        migrations.AlterField(
            model_name='absence',
            name='year',
            field=models.CharField(blank=True, choices=[('2021', '2021-2022'), ('2023', '2023-2024'), ('2024', '2024-2025'), ('2022', '2022-2023')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='boy',
            name='kind',
            field=models.CharField(choices=[('1', 'ذكر'), ('2', 'انثى')], default='1', max_length=50, verbose_name='النوع'),
        ),
        migrations.AlterField(
            model_name='boy',
            name='semester',
            field=models.CharField(blank=True, choices=[('first', 'الفصل الدراسي الاول'), ('second', 'الفصل الدراسي الثاني')], max_length=50, null=True, verbose_name='الفصل الدراسي'),
        ),
        migrations.AlterField(
            model_name='boy',
            name='year',
            field=models.CharField(blank=True, choices=[('2021', '2021-2022'), ('2023', '2023-2024'), ('2024', '2024-2025'), ('2022', '2022-2023')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='classes',
            name='semester',
            field=models.CharField(blank=True, choices=[('first', 'الفصل الدراسي الاول'), ('second', 'الفصل الدراسي الثاني')], max_length=50, null=True, verbose_name='الفصل الدراسي'),
        ),
        migrations.AlterField(
            model_name='classes',
            name='year',
            field=models.CharField(blank=True, choices=[('2021', '2021-2022'), ('2023', '2023-2024'), ('2024', '2024-2025'), ('2022', '2022-2023')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='darajat',
            name='semester',
            field=models.CharField(blank=True, choices=[('first', 'الفصل الدراسي الاول'), ('second', 'الفصل الدراسي الثاني')], max_length=50, null=True, verbose_name='الفصل الدراسي'),
        ),
        migrations.AlterField(
            model_name='darajat',
            name='year',
            field=models.CharField(blank=True, choices=[('2021', '2021-2022'), ('2023', '2023-2024'), ('2024', '2024-2025'), ('2022', '2022-2023')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='semester',
            field=models.CharField(blank=True, choices=[('first', 'الفصل الدراسي الاول'), ('second', 'الفصل الدراسي الثاني')], max_length=50, null=True, verbose_name='الفصل الدراسي'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='year',
            field=models.CharField(blank=True, choices=[('2021', '2021-2022'), ('2023', '2023-2024'), ('2024', '2024-2025'), ('2022', '2022-2023')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='masrof',
            name='semester',
            field=models.CharField(blank=True, choices=[('first', 'الفصل الدراسي الاول'), ('second', 'الفصل الدراسي الثاني')], max_length=50, null=True, verbose_name='الفصل الدراسي'),
        ),
        migrations.AlterField(
            model_name='masrof',
            name='year',
            field=models.CharField(blank=True, choices=[('2021', '2021-2022'), ('2023', '2023-2024'), ('2024', '2024-2025'), ('2022', '2022-2023')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mawad',
            name='semester',
            field=models.CharField(blank=True, choices=[('first', 'الفصل الدراسي الاول'), ('second', 'الفصل الدراسي الثاني')], max_length=50, null=True, verbose_name='الفصل الدراسي'),
        ),
        migrations.AlterField(
            model_name='mawad',
            name='year',
            field=models.CharField(blank=True, choices=[('2021', '2021-2022'), ('2023', '2023-2024'), ('2024', '2024-2025'), ('2022', '2022-2023')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='monthly_exams',
            name='month',
            field=models.CharField(blank=True, choices=[('4', 'أبريل'), ('1', 'يناير'), ('6', 'يونيو'), ('5', 'مايو'), ('2', 'فبراير'), ('3', 'مارس'), ('10', 'أكتوبر'), ('11', 'نوفمبر'), ('8', 'أغسطس'), ('7', 'يوليو'), ('12', 'ديسمبر'), ('9', 'سبتمبر')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='monthly_exams',
            name='year',
            field=models.CharField(blank=True, choices=[('2021', '2021-2022'), ('2023', '2023-2024'), ('2024', '2024-2025'), ('2022', '2022-2023')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='semester',
            field=models.CharField(choices=[('first', 'الفصل الدراسي الاول'), ('second', 'الفصل الدراسي الثاني')], max_length=50, verbose_name='الفصل الدراسي'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='month',
            field=models.CharField(blank=True, choices=[('4', 'أبريل'), ('1', 'يناير'), ('6', 'يونيو'), ('5', 'مايو'), ('2', 'فبراير'), ('3', 'مارس'), ('10', 'أكتوبر'), ('11', 'نوفمبر'), ('8', 'أغسطس'), ('7', 'يوليو'), ('12', 'ديسمبر'), ('9', 'سبتمبر')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='year',
            field=models.CharField(blank=True, choices=[('2021', '2021-2022'), ('2023', '2023-2024'), ('2024', '2024-2025'), ('2022', '2022-2023')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='staff_absence',
            name='month',
            field=models.CharField(blank=True, choices=[('4', 'أبريل'), ('1', 'يناير'), ('6', 'يونيو'), ('5', 'مايو'), ('2', 'فبراير'), ('3', 'مارس'), ('10', 'أكتوبر'), ('11', 'نوفمبر'), ('8', 'أغسطس'), ('7', 'يوليو'), ('12', 'ديسمبر'), ('9', 'سبتمبر')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='staff_absence',
            name='year',
            field=models.CharField(blank=True, choices=[('2021', '2021-2022'), ('2023', '2023-2024'), ('2024', '2024-2025'), ('2022', '2022-2023')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='teachers_absence',
            name='month',
            field=models.CharField(blank=True, choices=[('4', 'أبريل'), ('1', 'يناير'), ('6', 'يونيو'), ('5', 'مايو'), ('2', 'فبراير'), ('3', 'مارس'), ('10', 'أكتوبر'), ('11', 'نوفمبر'), ('8', 'أغسطس'), ('7', 'يوليو'), ('12', 'ديسمبر'), ('9', 'سبتمبر')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='teachers_absence',
            name='year',
            field=models.CharField(blank=True, choices=[('2021', '2021-2022'), ('2023', '2023-2024'), ('2024', '2024-2025'), ('2022', '2022-2023')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='techers',
            name='semester',
            field=models.CharField(blank=True, choices=[('first', 'الفصل الدراسي الاول'), ('second', 'الفصل الدراسي الثاني')], max_length=50, null=True, verbose_name='الفصل الدراسي'),
        ),
        migrations.AlterField(
            model_name='techers',
            name='year',
            field=models.CharField(blank=True, choices=[('2021', '2021-2022'), ('2023', '2023-2024'), ('2024', '2024-2025'), ('2022', '2022-2023')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='transport',
            name='kind',
            field=models.CharField(choices=[('تكتك', 'تكتك'), ('ميكروباس', 'ميكروباس'), ('اتوبيس', 'اتوبيس'), ('سيارة', 'سيارة')], max_length=50, verbose_name='نوع وسيلة النقل'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='semester',
            field=models.CharField(blank=True, choices=[('first', 'الفصل الدراسي الاول'), ('second', 'الفصل الدراسي الثاني')], max_length=50, null=True, verbose_name='الفصل الدراسي'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='year',
            field=models.CharField(blank=True, choices=[('2021', '2021-2022'), ('2023', '2023-2024'), ('2024', '2024-2025'), ('2022', '2022-2023')], max_length=50, null=True),
        ),
    ]
