# Generated by Django 4.0.4 on 2022-06-01 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0059_staff_age_alter_absence_semester_alter_absence_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='number_kawme',
            field=models.IntegerField(blank=True, null=True, verbose_name='الرقم القومي'),
        ),
        migrations.AddField(
            model_name='staff',
            name='number_phone',
            field=models.IntegerField(blank=True, null=True, verbose_name='رقم ولي الامر'),
        ),
        migrations.AlterField(
            model_name='absence',
            name='year',
            field=models.CharField(blank=True, choices=[('2022', '2022-2023'), ('2023', '2023-2024'), ('2021', '2021-2022'), ('2024', '2024-2025')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='boy',
            name='age',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='السن'),
        ),
        migrations.AlterField(
            model_name='boy',
            name='year',
            field=models.CharField(blank=True, choices=[('2022', '2022-2023'), ('2023', '2023-2024'), ('2021', '2021-2022'), ('2024', '2024-2025')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='classes',
            name='year',
            field=models.CharField(blank=True, choices=[('2022', '2022-2023'), ('2023', '2023-2024'), ('2021', '2021-2022'), ('2024', '2024-2025')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='darajat',
            name='year',
            field=models.CharField(blank=True, choices=[('2022', '2022-2023'), ('2023', '2023-2024'), ('2021', '2021-2022'), ('2024', '2024-2025')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='year',
            field=models.CharField(blank=True, choices=[('2022', '2022-2023'), ('2023', '2023-2024'), ('2021', '2021-2022'), ('2024', '2024-2025')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='masrof',
            name='year',
            field=models.CharField(blank=True, choices=[('2022', '2022-2023'), ('2023', '2023-2024'), ('2021', '2021-2022'), ('2024', '2024-2025')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mawad',
            name='year',
            field=models.CharField(blank=True, choices=[('2022', '2022-2023'), ('2023', '2023-2024'), ('2021', '2021-2022'), ('2024', '2024-2025')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='monthly_exams',
            name='month',
            field=models.CharField(blank=True, choices=[('3', 'مارس'), ('6', 'يونيو'), ('1', 'يناير'), ('12', 'ديسمبر'), ('5', 'مايو'), ('9', 'سبتمبر'), ('11', 'نوفمبر'), ('7', 'يوليو'), ('4', 'أبريل'), ('2', 'فبراير'), ('8', 'أغسطس'), ('10', 'أكتوبر')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='monthly_exams',
            name='year',
            field=models.CharField(blank=True, choices=[('2022', '2022-2023'), ('2023', '2023-2024'), ('2021', '2021-2022'), ('2024', '2024-2025')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='age',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='السن'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='month',
            field=models.CharField(blank=True, choices=[('3', 'مارس'), ('6', 'يونيو'), ('1', 'يناير'), ('12', 'ديسمبر'), ('5', 'مايو'), ('9', 'سبتمبر'), ('11', 'نوفمبر'), ('7', 'يوليو'), ('4', 'أبريل'), ('2', 'فبراير'), ('8', 'أغسطس'), ('10', 'أكتوبر')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='year',
            field=models.CharField(blank=True, choices=[('2022', '2022-2023'), ('2023', '2023-2024'), ('2021', '2021-2022'), ('2024', '2024-2025')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='staff_absence',
            name='month',
            field=models.CharField(blank=True, choices=[('3', 'مارس'), ('6', 'يونيو'), ('1', 'يناير'), ('12', 'ديسمبر'), ('5', 'مايو'), ('9', 'سبتمبر'), ('11', 'نوفمبر'), ('7', 'يوليو'), ('4', 'أبريل'), ('2', 'فبراير'), ('8', 'أغسطس'), ('10', 'أكتوبر')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='staff_absence',
            name='year',
            field=models.CharField(blank=True, choices=[('2022', '2022-2023'), ('2023', '2023-2024'), ('2021', '2021-2022'), ('2024', '2024-2025')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='teachers_absence',
            name='month',
            field=models.CharField(blank=True, choices=[('3', 'مارس'), ('6', 'يونيو'), ('1', 'يناير'), ('12', 'ديسمبر'), ('5', 'مايو'), ('9', 'سبتمبر'), ('11', 'نوفمبر'), ('7', 'يوليو'), ('4', 'أبريل'), ('2', 'فبراير'), ('8', 'أغسطس'), ('10', 'أكتوبر')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='teachers_absence',
            name='year',
            field=models.CharField(blank=True, choices=[('2022', '2022-2023'), ('2023', '2023-2024'), ('2021', '2021-2022'), ('2024', '2024-2025')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='techers',
            name='year',
            field=models.CharField(blank=True, choices=[('2022', '2022-2023'), ('2023', '2023-2024'), ('2021', '2021-2022'), ('2024', '2024-2025')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='transport',
            name='kind',
            field=models.CharField(choices=[('اتوبيس', 'اتوبيس'), ('سيارة', 'سيارة'), ('ميكروباس', 'ميكروباس'), ('تكتك', 'تكتك')], max_length=50, verbose_name='نوع وسيلة النقل'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='year',
            field=models.CharField(blank=True, choices=[('2022', '2022-2023'), ('2023', '2023-2024'), ('2021', '2021-2022'), ('2024', '2024-2025')], max_length=50, null=True),
        ),
    ]
