# Generated by Django 4.0.4 on 2022-06-02 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0061_remove_staff_absence_name_monthly_exams_semester_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff_absence',
            name='staff_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home_app.staff', verbose_name='اسم الموظف'),
        ),
        migrations.AlterField(
            model_name='absence',
            name='semester',
            field=models.CharField(blank=True, choices=[('first', 'الفصل الدراسي الاول'), ('second', 'الفصل الدراسي الثاني')], max_length=50, null=True, verbose_name='الفصل الدراسي'),
        ),
        migrations.AlterField(
            model_name='absence',
            name='year',
            field=models.CharField(blank=True, choices=[('2023', '2023-2024'), ('2024', '2024-2025'), ('2021', '2021-2022'), ('2022', '2022-2023')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='boy',
            name='kind',
            field=models.CharField(choices=[('1', 'ذكر'), ('2', 'انثى')], default='1', max_length=50, verbose_name='النوع'),
        ),
        migrations.AlterField(
            model_name='boy',
            name='semester',
            field=models.CharField(blank=True, choices=[('first', 'الفصل الدراسي الاول'), ('second', 'الفصل الدراسي الثاني')], max_length=50, null=True, verbose_name='الفصل الدراسي'),
        ),
        migrations.AlterField(
            model_name='boy',
            name='year',
            field=models.CharField(blank=True, choices=[('2023', '2023-2024'), ('2024', '2024-2025'), ('2021', '2021-2022'), ('2022', '2022-2023')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='classes',
            name='semester',
            field=models.CharField(blank=True, choices=[('first', 'الفصل الدراسي الاول'), ('second', 'الفصل الدراسي الثاني')], max_length=50, null=True, verbose_name='الفصل الدراسي'),
        ),
        migrations.AlterField(
            model_name='classes',
            name='year',
            field=models.CharField(blank=True, choices=[('2023', '2023-2024'), ('2024', '2024-2025'), ('2021', '2021-2022'), ('2022', '2022-2023')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='darajat',
            name='semester',
            field=models.CharField(blank=True, choices=[('first', 'الفصل الدراسي الاول'), ('second', 'الفصل الدراسي الثاني')], max_length=50, null=True, verbose_name='الفصل الدراسي'),
        ),
        migrations.AlterField(
            model_name='darajat',
            name='year',
            field=models.CharField(blank=True, choices=[('2023', '2023-2024'), ('2024', '2024-2025'), ('2021', '2021-2022'), ('2022', '2022-2023')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='semester',
            field=models.CharField(blank=True, choices=[('first', 'الفصل الدراسي الاول'), ('second', 'الفصل الدراسي الثاني')], max_length=50, null=True, verbose_name='الفصل الدراسي'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='year',
            field=models.CharField(blank=True, choices=[('2023', '2023-2024'), ('2024', '2024-2025'), ('2021', '2021-2022'), ('2022', '2022-2023')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='masrof',
            name='semester',
            field=models.CharField(blank=True, choices=[('first', 'الفصل الدراسي الاول'), ('second', 'الفصل الدراسي الثاني')], max_length=50, null=True, verbose_name='الفصل الدراسي'),
        ),
        migrations.AlterField(
            model_name='masrof',
            name='year',
            field=models.CharField(blank=True, choices=[('2023', '2023-2024'), ('2024', '2024-2025'), ('2021', '2021-2022'), ('2022', '2022-2023')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mawad',
            name='semester',
            field=models.CharField(blank=True, choices=[('first', 'الفصل الدراسي الاول'), ('second', 'الفصل الدراسي الثاني')], max_length=50, null=True, verbose_name='الفصل الدراسي'),
        ),
        migrations.AlterField(
            model_name='mawad',
            name='year',
            field=models.CharField(blank=True, choices=[('2023', '2023-2024'), ('2024', '2024-2025'), ('2021', '2021-2022'), ('2022', '2022-2023')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='monthly_exams',
            name='month',
            field=models.CharField(blank=True, choices=[('1', 'يناير'), ('8', 'أغسطس'), ('10', 'أكتوبر'), ('5', 'مايو'), ('7', 'يوليو'), ('4', 'أبريل'), ('9', 'سبتمبر'), ('6', 'يونيو'), ('12', 'ديسمبر'), ('2', 'فبراير'), ('11', 'نوفمبر'), ('3', 'مارس')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='monthly_exams',
            name='semester',
            field=models.CharField(blank=True, choices=[('first', 'الفصل الدراسي الاول'), ('second', 'الفصل الدراسي الثاني')], max_length=50, null=True, verbose_name='الفصل الدراسي'),
        ),
        migrations.AlterField(
            model_name='monthly_exams',
            name='year',
            field=models.CharField(blank=True, choices=[('2023', '2023-2024'), ('2024', '2024-2025'), ('2021', '2021-2022'), ('2022', '2022-2023')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='semester',
            field=models.CharField(choices=[('first', 'الفصل الدراسي الاول'), ('second', 'الفصل الدراسي الثاني')], max_length=50, verbose_name='الفصل الدراسي'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='month',
            field=models.CharField(blank=True, choices=[('1', 'يناير'), ('8', 'أغسطس'), ('10', 'أكتوبر'), ('5', 'مايو'), ('7', 'يوليو'), ('4', 'أبريل'), ('9', 'سبتمبر'), ('6', 'يونيو'), ('12', 'ديسمبر'), ('2', 'فبراير'), ('11', 'نوفمبر'), ('3', 'مارس')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='year',
            field=models.CharField(blank=True, choices=[('2023', '2023-2024'), ('2024', '2024-2025'), ('2021', '2021-2022'), ('2022', '2022-2023')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='staff_absence',
            name='month',
            field=models.CharField(blank=True, choices=[('1', 'يناير'), ('8', 'أغسطس'), ('10', 'أكتوبر'), ('5', 'مايو'), ('7', 'يوليو'), ('4', 'أبريل'), ('9', 'سبتمبر'), ('6', 'يونيو'), ('12', 'ديسمبر'), ('2', 'فبراير'), ('11', 'نوفمبر'), ('3', 'مارس')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='staff_absence',
            name='year',
            field=models.CharField(blank=True, choices=[('2023', '2023-2024'), ('2024', '2024-2025'), ('2021', '2021-2022'), ('2022', '2022-2023')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='teachers_absence',
            name='month',
            field=models.CharField(blank=True, choices=[('1', 'يناير'), ('8', 'أغسطس'), ('10', 'أكتوبر'), ('5', 'مايو'), ('7', 'يوليو'), ('4', 'أبريل'), ('9', 'سبتمبر'), ('6', 'يونيو'), ('12', 'ديسمبر'), ('2', 'فبراير'), ('11', 'نوفمبر'), ('3', 'مارس')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='teachers_absence',
            name='year',
            field=models.CharField(blank=True, choices=[('2023', '2023-2024'), ('2024', '2024-2025'), ('2021', '2021-2022'), ('2022', '2022-2023')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='techers',
            name='semester',
            field=models.CharField(blank=True, choices=[('first', 'الفصل الدراسي الاول'), ('second', 'الفصل الدراسي الثاني')], max_length=50, null=True, verbose_name='الفصل الدراسي'),
        ),
        migrations.AlterField(
            model_name='techers',
            name='year',
            field=models.CharField(blank=True, choices=[('2023', '2023-2024'), ('2024', '2024-2025'), ('2021', '2021-2022'), ('2022', '2022-2023')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='transport',
            name='kind',
            field=models.CharField(choices=[('ميكروباس', 'ميكروباس'), ('تكتك', 'تكتك'), ('سيارة', 'سيارة'), ('اتوبيس', 'اتوبيس')], max_length=50, verbose_name='نوع وسيلة النقل'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='semester',
            field=models.CharField(blank=True, choices=[('first', 'الفصل الدراسي الاول'), ('second', 'الفصل الدراسي الثاني')], max_length=50, null=True, verbose_name='الفصل الدراسي'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='year',
            field=models.CharField(blank=True, choices=[('2023', '2023-2024'), ('2024', '2024-2025'), ('2021', '2021-2022'), ('2022', '2022-2023')], max_length=50, null=True),
        ),
    ]
