# Generated by Django 4.0.4 on 2022-06-03 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0062_staff_absence_staff_name_alter_absence_semester_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absence',
            name='year',
            field=models.CharField(blank=True, choices=[('2024', '2024-2025'), ('2022', '2022-2023'), ('2021', '2021-2022'), ('2023', '2023-2024')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='boy',
            name='kind',
            field=models.CharField(choices=[('2', 'انثى'), ('1', 'ذكر')], default='1', max_length=50, verbose_name='النوع'),
        ),
        migrations.AlterField(
            model_name='boy',
            name='year',
            field=models.CharField(blank=True, choices=[('2024', '2024-2025'), ('2022', '2022-2023'), ('2021', '2021-2022'), ('2023', '2023-2024')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='classes',
            name='year',
            field=models.CharField(blank=True, choices=[('2024', '2024-2025'), ('2022', '2022-2023'), ('2021', '2021-2022'), ('2023', '2023-2024')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='darajat',
            name='year',
            field=models.CharField(blank=True, choices=[('2024', '2024-2025'), ('2022', '2022-2023'), ('2021', '2021-2022'), ('2023', '2023-2024')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='year',
            field=models.CharField(blank=True, choices=[('2024', '2024-2025'), ('2022', '2022-2023'), ('2021', '2021-2022'), ('2023', '2023-2024')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='masrof',
            name='year',
            field=models.CharField(blank=True, choices=[('2024', '2024-2025'), ('2022', '2022-2023'), ('2021', '2021-2022'), ('2023', '2023-2024')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mawad',
            name='year',
            field=models.CharField(blank=True, choices=[('2024', '2024-2025'), ('2022', '2022-2023'), ('2021', '2021-2022'), ('2023', '2023-2024')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='monthly_exams',
            name='month',
            field=models.CharField(blank=True, choices=[('1', 'يناير'), ('7', 'يوليو'), ('11', 'نوفمبر'), ('3', 'مارس'), ('8', 'أغسطس'), ('2', 'فبراير'), ('5', 'مايو'), ('12', 'ديسمبر'), ('9', 'سبتمبر'), ('6', 'يونيو'), ('4', 'أبريل'), ('10', 'أكتوبر')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='monthly_exams',
            name='year',
            field=models.CharField(blank=True, choices=[('2024', '2024-2025'), ('2022', '2022-2023'), ('2021', '2021-2022'), ('2023', '2023-2024')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='month',
            field=models.CharField(blank=True, choices=[('1', 'يناير'), ('7', 'يوليو'), ('11', 'نوفمبر'), ('3', 'مارس'), ('8', 'أغسطس'), ('2', 'فبراير'), ('5', 'مايو'), ('12', 'ديسمبر'), ('9', 'سبتمبر'), ('6', 'يونيو'), ('4', 'أبريل'), ('10', 'أكتوبر')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='year',
            field=models.CharField(blank=True, choices=[('2024', '2024-2025'), ('2022', '2022-2023'), ('2021', '2021-2022'), ('2023', '2023-2024')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='staff_absence',
            name='month',
            field=models.CharField(blank=True, choices=[('1', 'يناير'), ('7', 'يوليو'), ('11', 'نوفمبر'), ('3', 'مارس'), ('8', 'أغسطس'), ('2', 'فبراير'), ('5', 'مايو'), ('12', 'ديسمبر'), ('9', 'سبتمبر'), ('6', 'يونيو'), ('4', 'أبريل'), ('10', 'أكتوبر')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='staff_absence',
            name='year',
            field=models.CharField(blank=True, choices=[('2024', '2024-2025'), ('2022', '2022-2023'), ('2021', '2021-2022'), ('2023', '2023-2024')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='teachers_absence',
            name='month',
            field=models.CharField(blank=True, choices=[('1', 'يناير'), ('7', 'يوليو'), ('11', 'نوفمبر'), ('3', 'مارس'), ('8', 'أغسطس'), ('2', 'فبراير'), ('5', 'مايو'), ('12', 'ديسمبر'), ('9', 'سبتمبر'), ('6', 'يونيو'), ('4', 'أبريل'), ('10', 'أكتوبر')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='teachers_absence',
            name='year',
            field=models.CharField(blank=True, choices=[('2024', '2024-2025'), ('2022', '2022-2023'), ('2021', '2021-2022'), ('2023', '2023-2024')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='techers',
            name='year',
            field=models.CharField(blank=True, choices=[('2024', '2024-2025'), ('2022', '2022-2023'), ('2021', '2021-2022'), ('2023', '2023-2024')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='transport',
            name='kind',
            field=models.CharField(choices=[('اتوبيس', 'اتوبيس'), ('سيارة', 'سيارة'), ('ميكروباس', 'ميكروباس'), ('تكتك', 'تكتك')], max_length=50, verbose_name='نوع وسيلة النقل'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='year',
            field=models.CharField(blank=True, choices=[('2024', '2024-2025'), ('2022', '2022-2023'), ('2021', '2021-2022'), ('2023', '2023-2024')], max_length=50, null=True),
        ),
    ]
