# Generated by Django 4.0.4 on 2022-06-04 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0064_remove_boy_semester_alter_absence_semester_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teachers_absence',
            old_name='name',
            new_name='teacher_name',
        ),
        migrations.AlterField(
            model_name='absence',
            name='semester',
            field=models.CharField(blank=True, choices=[('first', 'الفصل الدراسي الاول'), ('second', 'الفصل الدراسي الثاني')], max_length=50, null=True, verbose_name='الفصل الدراسي'),
        ),
        migrations.AlterField(
            model_name='absence',
            name='year',
            field=models.CharField(blank=True, choices=[('2021', '2021-2022'), ('2023', '2023-2024'), ('2022', '2022-2023'), ('2024', '2024-2025')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='boy',
            name='kind',
            field=models.CharField(choices=[('1', 'ذكر'), ('2', 'انثى')], default='1', max_length=50, verbose_name='النوع'),
        ),
        migrations.AlterField(
            model_name='boy',
            name='year',
            field=models.CharField(blank=True, choices=[('2021', '2021-2022'), ('2023', '2023-2024'), ('2022', '2022-2023'), ('2024', '2024-2025')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='classes',
            name='semester',
            field=models.CharField(blank=True, choices=[('first', 'الفصل الدراسي الاول'), ('second', 'الفصل الدراسي الثاني')], max_length=50, null=True, verbose_name='الفصل الدراسي'),
        ),
        migrations.AlterField(
            model_name='classes',
            name='year',
            field=models.CharField(blank=True, choices=[('2021', '2021-2022'), ('2023', '2023-2024'), ('2022', '2022-2023'), ('2024', '2024-2025')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='darajat',
            name='semester',
            field=models.CharField(blank=True, choices=[('first', 'الفصل الدراسي الاول'), ('second', 'الفصل الدراسي الثاني')], max_length=50, null=True, verbose_name='الفصل الدراسي'),
        ),
        migrations.AlterField(
            model_name='darajat',
            name='year',
            field=models.CharField(blank=True, choices=[('2021', '2021-2022'), ('2023', '2023-2024'), ('2022', '2022-2023'), ('2024', '2024-2025')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='semester',
            field=models.CharField(blank=True, choices=[('first', 'الفصل الدراسي الاول'), ('second', 'الفصل الدراسي الثاني')], max_length=50, null=True, verbose_name='الفصل الدراسي'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='year',
            field=models.CharField(blank=True, choices=[('2021', '2021-2022'), ('2023', '2023-2024'), ('2022', '2022-2023'), ('2024', '2024-2025')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='masrof',
            name='semester',
            field=models.CharField(blank=True, choices=[('first', 'الفصل الدراسي الاول'), ('second', 'الفصل الدراسي الثاني')], max_length=50, null=True, verbose_name='الفصل الدراسي'),
        ),
        migrations.AlterField(
            model_name='masrof',
            name='year',
            field=models.CharField(blank=True, choices=[('2021', '2021-2022'), ('2023', '2023-2024'), ('2022', '2022-2023'), ('2024', '2024-2025')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mawad',
            name='semester',
            field=models.CharField(blank=True, choices=[('first', 'الفصل الدراسي الاول'), ('second', 'الفصل الدراسي الثاني')], max_length=50, null=True, verbose_name='الفصل الدراسي'),
        ),
        migrations.AlterField(
            model_name='mawad',
            name='year',
            field=models.CharField(blank=True, choices=[('2021', '2021-2022'), ('2023', '2023-2024'), ('2022', '2022-2023'), ('2024', '2024-2025')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='monthly_exams',
            name='month',
            field=models.CharField(blank=True, choices=[('4', 'أبريل'), ('11', 'نوفمبر'), ('8', 'أغسطس'), ('10', 'أكتوبر'), ('3', 'مارس'), ('7', 'يوليو'), ('2', 'فبراير'), ('12', 'ديسمبر'), ('9', 'سبتمبر'), ('1', 'يناير'), ('5', 'مايو'), ('6', 'يونيو')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='monthly_exams',
            name='semester',
            field=models.CharField(blank=True, choices=[('first', 'الفصل الدراسي الاول'), ('second', 'الفصل الدراسي الثاني')], max_length=50, null=True, verbose_name='الفصل الدراسي'),
        ),
        migrations.AlterField(
            model_name='monthly_exams',
            name='year',
            field=models.CharField(blank=True, choices=[('2021', '2021-2022'), ('2023', '2023-2024'), ('2022', '2022-2023'), ('2024', '2024-2025')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='semester',
            field=models.CharField(choices=[('first', 'الفصل الدراسي الاول'), ('second', 'الفصل الدراسي الثاني')], max_length=50, verbose_name='الفصل الدراسي'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='month',
            field=models.CharField(blank=True, choices=[('4', 'أبريل'), ('11', 'نوفمبر'), ('8', 'أغسطس'), ('10', 'أكتوبر'), ('3', 'مارس'), ('7', 'يوليو'), ('2', 'فبراير'), ('12', 'ديسمبر'), ('9', 'سبتمبر'), ('1', 'يناير'), ('5', 'مايو'), ('6', 'يونيو')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='year',
            field=models.CharField(blank=True, choices=[('2021', '2021-2022'), ('2023', '2023-2024'), ('2022', '2022-2023'), ('2024', '2024-2025')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='staff_absence',
            name='month',
            field=models.CharField(blank=True, choices=[('4', 'أبريل'), ('11', 'نوفمبر'), ('8', 'أغسطس'), ('10', 'أكتوبر'), ('3', 'مارس'), ('7', 'يوليو'), ('2', 'فبراير'), ('12', 'ديسمبر'), ('9', 'سبتمبر'), ('1', 'يناير'), ('5', 'مايو'), ('6', 'يونيو')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='staff_absence',
            name='year',
            field=models.CharField(blank=True, choices=[('2021', '2021-2022'), ('2023', '2023-2024'), ('2022', '2022-2023'), ('2024', '2024-2025')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='teachers_absence',
            name='month',
            field=models.CharField(blank=True, choices=[('4', 'أبريل'), ('11', 'نوفمبر'), ('8', 'أغسطس'), ('10', 'أكتوبر'), ('3', 'مارس'), ('7', 'يوليو'), ('2', 'فبراير'), ('12', 'ديسمبر'), ('9', 'سبتمبر'), ('1', 'يناير'), ('5', 'مايو'), ('6', 'يونيو')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='teachers_absence',
            name='year',
            field=models.CharField(blank=True, choices=[('2021', '2021-2022'), ('2023', '2023-2024'), ('2022', '2022-2023'), ('2024', '2024-2025')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='techers',
            name='semester',
            field=models.CharField(blank=True, choices=[('first', 'الفصل الدراسي الاول'), ('second', 'الفصل الدراسي الثاني')], max_length=50, null=True, verbose_name='الفصل الدراسي'),
        ),
        migrations.AlterField(
            model_name='techers',
            name='year',
            field=models.CharField(blank=True, choices=[('2021', '2021-2022'), ('2023', '2023-2024'), ('2022', '2022-2023'), ('2024', '2024-2025')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='transport',
            name='kind',
            field=models.CharField(choices=[('اتوبيس', 'اتوبيس'), ('سيارة', 'سيارة'), ('تكتك', 'تكتك'), ('ميكروباس', 'ميكروباس')], max_length=50, verbose_name='نوع وسيلة النقل'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='semester',
            field=models.CharField(blank=True, choices=[('first', 'الفصل الدراسي الاول'), ('second', 'الفصل الدراسي الثاني')], max_length=50, null=True, verbose_name='الفصل الدراسي'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='year',
            field=models.CharField(blank=True, choices=[('2021', '2021-2022'), ('2023', '2023-2024'), ('2022', '2022-2023'), ('2024', '2024-2025')], max_length=50, null=True),
        ),
    ]
