# Generated by Django 4.0.4 on 2022-06-07 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0066_alter_absence_semester_alter_absence_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='masrof',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home_app.profile', verbose_name='المستخدم'),
        ),
        migrations.AlterField(
            model_name='absence',
            name='year',
            field=models.CharField(blank=True, choices=[('2023', '2023-2024'), ('2021', '2021-2022'), ('2022', '2022-2023'), ('2024', '2024-2025')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='boy',
            name='kind',
            field=models.CharField(choices=[('انثى', 'انثى'), ('ذكر', 'ذكر')], default='1', max_length=50, verbose_name='النوع'),
        ),
        migrations.AlterField(
            model_name='boy',
            name='year',
            field=models.CharField(blank=True, choices=[('2023', '2023-2024'), ('2021', '2021-2022'), ('2022', '2022-2023'), ('2024', '2024-2025')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='classes',
            name='year',
            field=models.CharField(blank=True, choices=[('2023', '2023-2024'), ('2021', '2021-2022'), ('2022', '2022-2023'), ('2024', '2024-2025')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='darajat',
            name='year',
            field=models.CharField(blank=True, choices=[('2023', '2023-2024'), ('2021', '2021-2022'), ('2022', '2022-2023'), ('2024', '2024-2025')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='year',
            field=models.CharField(blank=True, choices=[('2023', '2023-2024'), ('2021', '2021-2022'), ('2022', '2022-2023'), ('2024', '2024-2025')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='masrof',
            name='year',
            field=models.CharField(blank=True, choices=[('2023', '2023-2024'), ('2021', '2021-2022'), ('2022', '2022-2023'), ('2024', '2024-2025')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mawad',
            name='year',
            field=models.CharField(blank=True, choices=[('2023', '2023-2024'), ('2021', '2021-2022'), ('2022', '2022-2023'), ('2024', '2024-2025')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='monthly_exams',
            name='month',
            field=models.CharField(blank=True, choices=[('4', 'أبريل'), ('10', 'أكتوبر'), ('6', 'يونيو'), ('3', 'مارس'), ('5', 'مايو'), ('12', 'ديسمبر'), ('11', 'نوفمبر'), ('9', 'سبتمبر'), ('7', 'يوليو'), ('2', 'فبراير'), ('1', 'يناير'), ('8', 'أغسطس')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='monthly_exams',
            name='year',
            field=models.CharField(blank=True, choices=[('2023', '2023-2024'), ('2021', '2021-2022'), ('2022', '2022-2023'), ('2024', '2024-2025')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='month',
            field=models.CharField(blank=True, choices=[('4', 'أبريل'), ('10', 'أكتوبر'), ('6', 'يونيو'), ('3', 'مارس'), ('5', 'مايو'), ('12', 'ديسمبر'), ('11', 'نوفمبر'), ('9', 'سبتمبر'), ('7', 'يوليو'), ('2', 'فبراير'), ('1', 'يناير'), ('8', 'أغسطس')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='year',
            field=models.CharField(blank=True, choices=[('2023', '2023-2024'), ('2021', '2021-2022'), ('2022', '2022-2023'), ('2024', '2024-2025')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='staff_absence',
            name='month',
            field=models.CharField(blank=True, choices=[('4', 'أبريل'), ('10', 'أكتوبر'), ('6', 'يونيو'), ('3', 'مارس'), ('5', 'مايو'), ('12', 'ديسمبر'), ('11', 'نوفمبر'), ('9', 'سبتمبر'), ('7', 'يوليو'), ('2', 'فبراير'), ('1', 'يناير'), ('8', 'أغسطس')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='staff_absence',
            name='year',
            field=models.CharField(blank=True, choices=[('2023', '2023-2024'), ('2021', '2021-2022'), ('2022', '2022-2023'), ('2024', '2024-2025')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='teachers_absence',
            name='month',
            field=models.CharField(blank=True, choices=[('4', 'أبريل'), ('10', 'أكتوبر'), ('6', 'يونيو'), ('3', 'مارس'), ('5', 'مايو'), ('12', 'ديسمبر'), ('11', 'نوفمبر'), ('9', 'سبتمبر'), ('7', 'يوليو'), ('2', 'فبراير'), ('1', 'يناير'), ('8', 'أغسطس')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='teachers_absence',
            name='year',
            field=models.CharField(blank=True, choices=[('2023', '2023-2024'), ('2021', '2021-2022'), ('2022', '2022-2023'), ('2024', '2024-2025')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='techers',
            name='year',
            field=models.CharField(blank=True, choices=[('2023', '2023-2024'), ('2021', '2021-2022'), ('2022', '2022-2023'), ('2024', '2024-2025')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='transport',
            name='year',
            field=models.CharField(blank=True, choices=[('2023', '2023-2024'), ('2021', '2021-2022'), ('2022', '2022-2023'), ('2024', '2024-2025')], max_length=50, null=True),
        ),
    ]
