# Generated by Django 4.0.4 on 2022-06-08 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0067_masrof_profile_alter_absence_year_alter_boy_kind_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classes',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='masrof',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='mawad',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='techers',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='transport',
            name='semester',
        ),
        migrations.AlterField(
            model_name='boy',
            name='kind',
            field=models.CharField(choices=[('ذكر', 'ذكر'), ('انثى', 'انثى')], default='1', max_length=50, verbose_name='النوع'),
        ),
        migrations.AlterField(
            model_name='monthly_exams',
            name='month',
            field=models.CharField(blank=True, choices=[('9', 'سبتمبر'), ('2', 'فبراير'), ('5', 'مايو'), ('4', 'أبريل'), ('3', 'مارس'), ('11', 'نوفمبر'), ('6', 'يونيو'), ('1', 'يناير'), ('7', 'يوليو'), ('10', 'أكتوبر'), ('12', 'ديسمبر'), ('8', 'أغسطس')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='month',
            field=models.CharField(blank=True, choices=[('9', 'سبتمبر'), ('2', 'فبراير'), ('5', 'مايو'), ('4', 'أبريل'), ('3', 'مارس'), ('11', 'نوفمبر'), ('6', 'يونيو'), ('1', 'يناير'), ('7', 'يوليو'), ('10', 'أكتوبر'), ('12', 'ديسمبر'), ('8', 'أغسطس')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='staff_absence',
            name='month',
            field=models.CharField(blank=True, choices=[('9', 'سبتمبر'), ('2', 'فبراير'), ('5', 'مايو'), ('4', 'أبريل'), ('3', 'مارس'), ('11', 'نوفمبر'), ('6', 'يونيو'), ('1', 'يناير'), ('7', 'يوليو'), ('10', 'أكتوبر'), ('12', 'ديسمبر'), ('8', 'أغسطس')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='teachers_absence',
            name='month',
            field=models.CharField(blank=True, choices=[('9', 'سبتمبر'), ('2', 'فبراير'), ('5', 'مايو'), ('4', 'أبريل'), ('3', 'مارس'), ('11', 'نوفمبر'), ('6', 'يونيو'), ('1', 'يناير'), ('7', 'يوليو'), ('10', 'أكتوبر'), ('12', 'ديسمبر'), ('8', 'أغسطس')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='transport',
            name='kind',
            field=models.CharField(choices=[('اتوبيس', 'اتوبيس'), ('سيارة', 'سيارة'), ('ميكروباس', 'ميكروباس'), ('تكتك', 'تكتك')], max_length=50, verbose_name='نوع وسيلة النقل'),
        ),
    ]
