# Generated by Django 4.0.4 on 2022-06-08 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0068_remove_classes_semester_remove_driver_semester_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='absence',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home_app.profile', verbose_name='المستخدم'),
        ),
        migrations.AlterField(
            model_name='absence',
            name='semester',
            field=models.CharField(blank=True, choices=[('first', 'الفصل الدراسي الاول'), ('second', 'الفصل الدراسي الثاني')], max_length=50, null=True, verbose_name='الفصل الدراسي'),
        ),
        migrations.AlterField(
            model_name='absence',
            name='year',
            field=models.CharField(blank=True, choices=[('2023', '2023-2024'), ('2022', '2022-2023'), ('2021', '2021-2022'), ('2024', '2024-2025')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='boy',
            name='kind',
            field=models.CharField(choices=[('انثى', 'انثى'), ('ذكر', 'ذكر')], default='1', max_length=50, verbose_name='النوع'),
        ),
        migrations.AlterField(
            model_name='boy',
            name='year',
            field=models.CharField(blank=True, choices=[('2023', '2023-2024'), ('2022', '2022-2023'), ('2021', '2021-2022'), ('2024', '2024-2025')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='classes',
            name='year',
            field=models.CharField(blank=True, choices=[('2023', '2023-2024'), ('2022', '2022-2023'), ('2021', '2021-2022'), ('2024', '2024-2025')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='darajat',
            name='semester',
            field=models.CharField(blank=True, choices=[('first', 'الفصل الدراسي الاول'), ('second', 'الفصل الدراسي الثاني')], max_length=50, null=True, verbose_name='الفصل الدراسي'),
        ),
        migrations.AlterField(
            model_name='darajat',
            name='year',
            field=models.CharField(blank=True, choices=[('2023', '2023-2024'), ('2022', '2022-2023'), ('2021', '2021-2022'), ('2024', '2024-2025')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='year',
            field=models.CharField(blank=True, choices=[('2023', '2023-2024'), ('2022', '2022-2023'), ('2021', '2021-2022'), ('2024', '2024-2025')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='masrof',
            name='year',
            field=models.CharField(blank=True, choices=[('2023', '2023-2024'), ('2022', '2022-2023'), ('2021', '2021-2022'), ('2024', '2024-2025')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mawad',
            name='year',
            field=models.CharField(blank=True, choices=[('2023', '2023-2024'), ('2022', '2022-2023'), ('2021', '2021-2022'), ('2024', '2024-2025')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='monthly_exams',
            name='month',
            field=models.CharField(blank=True, choices=[('6', 'يونيو'), ('5', 'مايو'), ('3', 'مارس'), ('12', 'ديسمبر'), ('4', 'أبريل'), ('2', 'فبراير'), ('7', 'يوليو'), ('10', 'أكتوبر'), ('11', 'نوفمبر'), ('1', 'يناير'), ('9', 'سبتمبر'), ('8', 'أغسطس')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='monthly_exams',
            name='semester',
            field=models.CharField(blank=True, choices=[('first', 'الفصل الدراسي الاول'), ('second', 'الفصل الدراسي الثاني')], max_length=50, null=True, verbose_name='الفصل الدراسي'),
        ),
        migrations.AlterField(
            model_name='monthly_exams',
            name='year',
            field=models.CharField(blank=True, choices=[('2023', '2023-2024'), ('2022', '2022-2023'), ('2021', '2021-2022'), ('2024', '2024-2025')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='semester',
            field=models.CharField(choices=[('first', 'الفصل الدراسي الاول'), ('second', 'الفصل الدراسي الثاني')], max_length=50, verbose_name='الفصل الدراسي'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='month',
            field=models.CharField(blank=True, choices=[('6', 'يونيو'), ('5', 'مايو'), ('3', 'مارس'), ('12', 'ديسمبر'), ('4', 'أبريل'), ('2', 'فبراير'), ('7', 'يوليو'), ('10', 'أكتوبر'), ('11', 'نوفمبر'), ('1', 'يناير'), ('9', 'سبتمبر'), ('8', 'أغسطس')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='year',
            field=models.CharField(blank=True, choices=[('2023', '2023-2024'), ('2022', '2022-2023'), ('2021', '2021-2022'), ('2024', '2024-2025')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='staff_absence',
            name='month',
            field=models.CharField(blank=True, choices=[('6', 'يونيو'), ('5', 'مايو'), ('3', 'مارس'), ('12', 'ديسمبر'), ('4', 'أبريل'), ('2', 'فبراير'), ('7', 'يوليو'), ('10', 'أكتوبر'), ('11', 'نوفمبر'), ('1', 'يناير'), ('9', 'سبتمبر'), ('8', 'أغسطس')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='staff_absence',
            name='year',
            field=models.CharField(blank=True, choices=[('2023', '2023-2024'), ('2022', '2022-2023'), ('2021', '2021-2022'), ('2024', '2024-2025')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='teachers_absence',
            name='month',
            field=models.CharField(blank=True, choices=[('6', 'يونيو'), ('5', 'مايو'), ('3', 'مارس'), ('12', 'ديسمبر'), ('4', 'أبريل'), ('2', 'فبراير'), ('7', 'يوليو'), ('10', 'أكتوبر'), ('11', 'نوفمبر'), ('1', 'يناير'), ('9', 'سبتمبر'), ('8', 'أغسطس')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='teachers_absence',
            name='year',
            field=models.CharField(blank=True, choices=[('2023', '2023-2024'), ('2022', '2022-2023'), ('2021', '2021-2022'), ('2024', '2024-2025')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='techers',
            name='year',
            field=models.CharField(blank=True, choices=[('2023', '2023-2024'), ('2022', '2022-2023'), ('2021', '2021-2022'), ('2024', '2024-2025')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='transport',
            name='kind',
            field=models.CharField(choices=[('ميكروباس', 'ميكروباس'), ('سيارة', 'سيارة'), ('تكتك', 'تكتك'), ('اتوبيس', 'اتوبيس')], max_length=50, verbose_name='نوع وسيلة النقل'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='year',
            field=models.CharField(blank=True, choices=[('2023', '2023-2024'), ('2022', '2022-2023'), ('2021', '2021-2022'), ('2024', '2024-2025')], max_length=50, null=True),
        ),
    ]
