# Generated by Django 4.0.4 on 2022-06-08 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0069_absence_profile_alter_absence_semester_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='month',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='year',
        ),
        migrations.AlterField(
            model_name='absence',
            name='year',
            field=models.CharField(blank=True, choices=[('2021', '2021-2022'), ('2022', '2022-2023'), ('2024', '2024-2025'), ('2023', '2023-2024')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='boy',
            name='year',
            field=models.CharField(blank=True, choices=[('2021', '2021-2022'), ('2022', '2022-2023'), ('2024', '2024-2025'), ('2023', '2023-2024')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='classes',
            name='year',
            field=models.CharField(blank=True, choices=[('2021', '2021-2022'), ('2022', '2022-2023'), ('2024', '2024-2025'), ('2023', '2023-2024')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='darajat',
            name='year',
            field=models.CharField(blank=True, choices=[('2021', '2021-2022'), ('2022', '2022-2023'), ('2024', '2024-2025'), ('2023', '2023-2024')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='year',
            field=models.CharField(blank=True, choices=[('2021', '2021-2022'), ('2022', '2022-2023'), ('2024', '2024-2025'), ('2023', '2023-2024')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='masrof',
            name='year',
            field=models.CharField(blank=True, choices=[('2021', '2021-2022'), ('2022', '2022-2023'), ('2024', '2024-2025'), ('2023', '2023-2024')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mawad',
            name='year',
            field=models.CharField(blank=True, choices=[('2021', '2021-2022'), ('2022', '2022-2023'), ('2024', '2024-2025'), ('2023', '2023-2024')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='monthly_exams',
            name='month',
            field=models.CharField(blank=True, choices=[('6', 'يونيو'), ('1', 'يناير'), ('11', 'نوفمبر'), ('8', 'أغسطس'), ('9', 'سبتمبر'), ('10', 'أكتوبر'), ('7', 'يوليو'), ('4', 'أبريل'), ('3', 'مارس'), ('12', 'ديسمبر'), ('5', 'مايو'), ('2', 'فبراير')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='monthly_exams',
            name='year',
            field=models.CharField(blank=True, choices=[('2021', '2021-2022'), ('2022', '2022-2023'), ('2024', '2024-2025'), ('2023', '2023-2024')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='number_phone',
            field=models.IntegerField(blank=True, null=True, verbose_name='رقم الهاتف'),
        ),
        migrations.AlterField(
            model_name='staff_absence',
            name='month',
            field=models.CharField(blank=True, choices=[('6', 'يونيو'), ('1', 'يناير'), ('11', 'نوفمبر'), ('8', 'أغسطس'), ('9', 'سبتمبر'), ('10', 'أكتوبر'), ('7', 'يوليو'), ('4', 'أبريل'), ('3', 'مارس'), ('12', 'ديسمبر'), ('5', 'مايو'), ('2', 'فبراير')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='staff_absence',
            name='year',
            field=models.CharField(blank=True, choices=[('2021', '2021-2022'), ('2022', '2022-2023'), ('2024', '2024-2025'), ('2023', '2023-2024')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='teachers_absence',
            name='month',
            field=models.CharField(blank=True, choices=[('6', 'يونيو'), ('1', 'يناير'), ('11', 'نوفمبر'), ('8', 'أغسطس'), ('9', 'سبتمبر'), ('10', 'أكتوبر'), ('7', 'يوليو'), ('4', 'أبريل'), ('3', 'مارس'), ('12', 'ديسمبر'), ('5', 'مايو'), ('2', 'فبراير')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='teachers_absence',
            name='year',
            field=models.CharField(blank=True, choices=[('2021', '2021-2022'), ('2022', '2022-2023'), ('2024', '2024-2025'), ('2023', '2023-2024')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='techers',
            name='year',
            field=models.CharField(blank=True, choices=[('2021', '2021-2022'), ('2022', '2022-2023'), ('2024', '2024-2025'), ('2023', '2023-2024')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='transport',
            name='kind',
            field=models.CharField(choices=[('سيارة', 'سيارة'), ('تكتك', 'تكتك'), ('ميكروباس', 'ميكروباس'), ('اتوبيس', 'اتوبيس')], max_length=50, verbose_name='نوع وسيلة النقل'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='year',
            field=models.CharField(blank=True, choices=[('2021', '2021-2022'), ('2022', '2022-2023'), ('2024', '2024-2025'), ('2023', '2023-2024')], max_length=50, null=True),
        ),
    ]
