# Generated by Django 4.0.4 on 2022-06-08 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0070_remove_staff_month_remove_staff_year_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mawad',
            name='year',
        ),
        migrations.AlterField(
            model_name='absence',
            name='year',
            field=models.CharField(blank=True, choices=[('2021', '2021-2022'), ('2024', '2024-2025'), ('2023', '2023-2024'), ('2022', '2022-2023')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='boy',
            name='kind',
            field=models.CharField(choices=[('ذكر', 'ذكر'), ('انثى', 'انثى')], default='1', max_length=50, verbose_name='النوع'),
        ),
        migrations.AlterField(
            model_name='boy',
            name='year',
            field=models.CharField(blank=True, choices=[('2021', '2021-2022'), ('2024', '2024-2025'), ('2023', '2023-2024'), ('2022', '2022-2023')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='classes',
            name='year',
            field=models.CharField(blank=True, choices=[('2021', '2021-2022'), ('2024', '2024-2025'), ('2023', '2023-2024'), ('2022', '2022-2023')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='darajat',
            name='year',
            field=models.CharField(blank=True, choices=[('2021', '2021-2022'), ('2024', '2024-2025'), ('2023', '2023-2024'), ('2022', '2022-2023')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='year',
            field=models.CharField(blank=True, choices=[('2021', '2021-2022'), ('2024', '2024-2025'), ('2023', '2023-2024'), ('2022', '2022-2023')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='masrof',
            name='year',
            field=models.CharField(blank=True, choices=[('2021', '2021-2022'), ('2024', '2024-2025'), ('2023', '2023-2024'), ('2022', '2022-2023')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='monthly_exams',
            name='month',
            field=models.CharField(blank=True, choices=[('8', 'أغسطس'), ('11', 'نوفمبر'), ('1', 'يناير'), ('2', 'فبراير'), ('3', 'مارس'), ('5', 'مايو'), ('4', 'أبريل'), ('6', 'يونيو'), ('7', 'يوليو'), ('12', 'ديسمبر'), ('9', 'سبتمبر'), ('10', 'أكتوبر')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='monthly_exams',
            name='year',
            field=models.CharField(blank=True, choices=[('2021', '2021-2022'), ('2024', '2024-2025'), ('2023', '2023-2024'), ('2022', '2022-2023')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='staff_absence',
            name='month',
            field=models.CharField(blank=True, choices=[('8', 'أغسطس'), ('11', 'نوفمبر'), ('1', 'يناير'), ('2', 'فبراير'), ('3', 'مارس'), ('5', 'مايو'), ('4', 'أبريل'), ('6', 'يونيو'), ('7', 'يوليو'), ('12', 'ديسمبر'), ('9', 'سبتمبر'), ('10', 'أكتوبر')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='staff_absence',
            name='year',
            field=models.CharField(blank=True, choices=[('2021', '2021-2022'), ('2024', '2024-2025'), ('2023', '2023-2024'), ('2022', '2022-2023')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='teachers_absence',
            name='month',
            field=models.CharField(blank=True, choices=[('8', 'أغسطس'), ('11', 'نوفمبر'), ('1', 'يناير'), ('2', 'فبراير'), ('3', 'مارس'), ('5', 'مايو'), ('4', 'أبريل'), ('6', 'يونيو'), ('7', 'يوليو'), ('12', 'ديسمبر'), ('9', 'سبتمبر'), ('10', 'أكتوبر')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='teachers_absence',
            name='year',
            field=models.CharField(blank=True, choices=[('2021', '2021-2022'), ('2024', '2024-2025'), ('2023', '2023-2024'), ('2022', '2022-2023')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='techers',
            name='year',
            field=models.CharField(blank=True, choices=[('2021', '2021-2022'), ('2024', '2024-2025'), ('2023', '2023-2024'), ('2022', '2022-2023')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='transport',
            name='kind',
            field=models.CharField(choices=[('اتوبيس', 'اتوبيس'), ('تكتك', 'تكتك'), ('سيارة', 'سيارة'), ('ميكروباس', 'ميكروباس')], max_length=50, verbose_name='نوع وسيلة النقل'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='year',
            field=models.CharField(blank=True, choices=[('2021', '2021-2022'), ('2024', '2024-2025'), ('2023', '2023-2024'), ('2022', '2022-2023')], max_length=50, null=True),
        ),
    ]
